version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.network=traefik_public
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
#     *** CAMBIAR EL EMAIL EN LA LINEA DE ABAJO ***
      - --certificatesresolvers.le.acme.email=socger@gmail.com
#     *** CAMBIAR EL EMAIL EN LA LINEA DE ARRIBA ***
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

    ports:
      - "80:80"

      - "443:443"
    volumes:
      - traefik_certificates:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik_public

#volumes:
#  traefik_certificates:
#    external: true
#    name: certificados
volumes:
  traefik_certificates:
    driver: local
    driver_opts:
      type: none
      device: /docker/traefik/certificados
      o: bind

networks:
  traefik_public:
    external: true
    attachable: true