version: "3.8"

services:
  duckdns_1:
    image: lscr.io/linuxserver/duckdns:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=cortinascristobal-po
      - TOKEN=28ec1a72-a87f-4fb1-a8b1-558f21ccf617
      - UPDATE_IP=ipv4
    volumes:
      - /docker/duckdns/cristobal/config:/config

  duckdns_2:
    image: lscr.io/linuxserver/duckdns:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=cortinascristobal-fs
      - TOKEN=28ec1a72-a87f-4fb1-a8b1-558f21ccf617
      - UPDATE_IP=ipv4
    volumes:
      - /docker/duckdns/cristobal/config:/config

  duckdns_3:
    image: lscr.io/linuxserver/duckdns:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=cuidamet
      - TOKEN=28ec1a72-a87f-4fb1-a8b1-558f21ccf617
      - UPDATE_IP=ipv4
    volumes:
      - /docker/duckdns/cristobal/config:/config
